FROM node:16.15.1-alpine as react-builder

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY client/package.json ./
COPY client/package-lock.json ./

RUN npm ci

COPY client/src ./src
COPY client/public ./public
COPY client/tsconfig.json ./

# RUN npm test
RUN npm run build

FROM nginx:latest as deploy

COPY --from=react-builder /app/build /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
