jdbc.url=jdbc:h2:mem:test
jdbc.driver=org.h2.Driver

hibernate.dialect=org.hibernate.dialect.H2Dialect
hibernate.hbm2ddl.auto=create
hibernate.show_sql=false

mail.sender.email=yggdrasil@darthgeek.us
mail.sender.name=Yggdrasil Dev Server

account.unverified.expiration=24

mail.link.validFor=120
mail.link.holdoff=30
